### PR TITLE
Hot reload configuration

### PR DESCRIPTION
**Pull request by joggee-fr**
This PR mainly add hot reload mechanism when changing add-on preferences. It avoids to refresh the opened YouTube page to apply newly selected options. It works sending message from options script to tabs containing content script. The configuration is then reloaded when receiving such a message.

I have done some tests but of course should be validated by other users here.
Thanks.

### CODE REVIEW

**Comment by gurumukhi** [comment]
Thanks for taking it up @joggee-fr :)

Code changes looks good to me. I wont have time to test it myself for some time, but lets hope if someone else can test it well.

**Comment by gurumukhi** [comment]
Also, I hope these changes will work well with our future idea of moving options to toolbar popup dialog (https://github.com/gurumukhi/youtube-screenshot/issues/23).

**Comment by joggee-fr** [comment]
> Also, I hope these changes will work well with our future idea of moving options to toolbar popup dialog (#23).

I did not check yet how to create toolbar popup for add-ons. However, according to documentation, the used mechanism to send message to content script is usable from all background scripts whatever is it from options or toolbar popup.

I hope someone here could try this PR...

**Comment by joggee-fr** [comment]
@PRIXYY, as you have been active recently on an other issue... maybe you could give my PR a try 😄 .

**Comment by joggee-fr** [comment]
I have just fixed an issue with logger not able to be disabled using hot reload.
Anyone to accept or reject my PR 😥 ?

**Comment by PRIXYY** [comment]
I am currently testing your changes joggee

**Comment by PRIXYY** [comment]
I have tested the addon and so far there has been no bugs ,I have tested it on different quality ,full screen ,in incoginto ,etc.Seems to be working fine.

**Comment by joggee-fr** [comment]
Replaced by PR #48.

**Pull request closed without merging**
