### PR TITLE
Add Screenshot button on Youtube Shorts

### PR DESCRIPTION
**Pull request by joggee-fr**
Main feature in this PR is adding Screenshot button to Youtube Shorts.
Some minor fixes are also included here including one for issue #29.

Opened as draft first to start the discussion. Main concern is about `MutationObserver` now always on.

### CODE REVIEW

**Comment by joggee-fr** [comment]
Just pinging the last contributors (testing or dev) if they can take a look at this PR:
- @thepwrtank18 
- @tacohitbox 
- @PRIXYY
- @RyutoSetsujin

**Comment by gurumukhi** [comment]
Code looks good to me, need to do rigorous testing.

Do you think we should try to streamline `addButtonOnRegularPlayer` & `addButtonOnShortsPlayer` methods? 
- One way to do this is by writing a single method with params, it will have many if-else blocks I think. 
- Another way is by taking out common functionalities out if that really makes code more maintainable.

**Comment by joggee-fr** [comment]
> Do you think we should try to streamline `addButtonOnRegularPlayer` & `addButtonOnShortsPlayer` methods?

You're right. Start and end of this two functions are analogue or similar and may be factorized.

**Comment by joggee-fr** [comment]
@gurumukhi
If possible during your tests, could you check if the patch have an impact on page loading performance also?
Thanks.

**Comment by joggee-fr** [comment]
@gurumukhi, I have factorized the functions adding the screenshot button and done a bit of tests to check it. Seems OK.
I am now considering this PR as ready for review 🙂 . Let me know if you find any issue during your tests. Thanks.

**Comment by gurumukhi** [comment]
This looks amazing, thanks a lot @joggee-fr :)

It looks like at some point we missed `logger` method's implementation during refactoring, can you look into this? I will merge the PR after that and release another version.

**Comment by joggee-fr** [comment]
@gurumukhi, this [commit](https://github.com/gurumukhi/youtube-screenshot/pull/30/commits/1e19d85b2c15f05e08b71fb6d806939d3be4c9da) tries to change the way `logger()` is managed to avoid always checking if a global variable is set or not. It is really a minor change and we can drop it.

The only thing I am less comfortable with is I only had to edit the global variable at top of file before to force logging during dev and debug. However, a new global variable can always be added to force `logger()` to output in console even if the dedicated add-on preference is not set.

**Comment by gurumukhi** [comment]
Sure, merging it. 👍

**Pull request merged**
