### PR TITLE
Add an option to copy screenshot to clipboard

### PR DESCRIPTION
**Pull request by joggee-fr**
Use a background script companion to access clipboard.
Note the selected API `browser.clipboard.setImageData()` is only supported by Firefox.
Also add a notification to indicate copy success.

Linked to issue #8.

### CODE REVIEW

**Comment by gurumukhi** [comment]
Noticed few issues, lets test it more.

One issue I noticed was addition of duplicate button on disabling & enabling the add-on. It can be avoided by simply adding something like this -

```
  if(document.querySelector('button.ytp-screenshot')) {
	logger('Button already added');
	return;
  }
```

Apart from this, I was able to test copy to clipboard feature initially, but after a while it started breaking. I dont know exact issue but we can test it further to see if we find any other issue.

We should also specify this on the options page itself - 'Reload the Youtube page to apply these settings'. In case user change button action & tries it without reloading Youtube page it wont work.

Thanks :)

**Comment by joggee-fr** [comment]
> One issue I noticed was addition of duplicate button on disabling & enabling the add-on. It can be avoided by simply adding something like this -
> 
> ```
>   if(document.querySelector('button.ytp-screenshot')) {
> 	logger('Button already added');
> 	return;
>   }
> ```

You're right. As this is a different issue, I will try to open an other PR to fix it with a slightly modified patch.

**Comment by PRIXYY** [comment]
I can try the updated version and see if I notice any issues.

**Comment by joggee-fr** [comment]
After rebase and quick tests, I did not notice any issue yet.
@PRIXYY, @gurumukhi, let me know if you detect any bug after trying. 

I agree adding "Reload the Youtube page to apply these settings" in settings page would be a nice feature. However, I think we can postpone it to another next PR.

**Comment by joggee-fr** [comment]
Any update?

**Comment by PRIXYY** [comment]
I have tested it. The 'copy to clipboard' feature is working properly.

**Comment by gurumukhi** [comment]
Great, I will merge it.

**Comment by gurumukhi** [comment]
Thanks a lot @joggee-fr and @PRIXYY

**Pull request merged**
